include_recipe 'build-essential::default'
include_recipe 'python::pip'
include_recipe 'python::virtualenv'

package 'postgresql-devel'
package 'python-devel'
package 'openssl-devel'
package 'httpd-tools'
package 'pcre'
package 'pcre-devel'
python_pip 'uwsgi'
